[package]
name = "sketchbook-ng"
version = "0.1.0"
authors = ["Danila Shutov <dcbrwn2@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.63"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
opt-level = "s"
